### ISSUE TITLE
Woningtype code 255

### ISSUE THREAD

**Issue by baasgeo** [geoparaat/bag#1]
In kolom woningtype van de tabel bag_snapshot_pand komt de waarde 255 voor terwijl deze waarde niet voorkomt in de opzoektabel bag_snapshot pand_woningtype

**Comment by MaartenHilferink** [comment]
255 betekent hier: no-data; waarschijnlijk betreft het panden die geen woningen bevatten. 

Het zou beter zijn aan woningtype het type 'geen woning' met een aansluitend volgnummer toe te voegen.
