### ISSUE TITLE
statuscode Pand: 1 tm 10

### ISSUE THREAD

**Issue by ThomasHaarlem** [geoparaat/bag#3]
Kijk ik er overheen of kan ik nergens een uitleg vinden welke statuscode bij welke pandstatus hoort?
Ik heb het idee dat 5. staat voor Pand in Gebruik. 
en dan komt het ook overeen met dit lijstje:
https://imbag.github.io/praktijkhandleiding/artikelen/welke-statussen-kent-de-BAG-en-wat-betekenen-deze-statussen

maar zeker is het niet en vind het vrij riskant om er blind van uit te gaan dat diezelfde volgorde is aangehouden.

**Comment by baasgeo** [comment]
Beste Thomas, inmiddels levert het Kadaster een geopackage van de BAG. Hierdoor is geoparaat niet meer nodig en daarom gaan we het project stoppen.

BAG GeoPackage: https://www.kadaster.nl/zakelijk/producten/adressen-en-gebouwen/bag-geopackage
